### ISSUE TITLE
Training time, etc

### ISSUE THREAD

**Issue by palmdong** [valeoai/rangevit#7]
Hi @gidariss, thanks for your interesting work.

Could you share about
(1) how long did it take for training on nuScenes? 
(2) how many gpus did you use? and the type of the gpus?

I look forward to your kind reply, thanks!

**Comment by angelika1108** [comment]
Hi @palmdong! We thank you very much for your question.
(1) The training on nuScenes took 18 hours,
(2) with 4 Nvidia V100 (32GB) GPUs.
The inference time on nuScenes (Table 10 in the Supplementary material) was calculated using the same GeForce RTX 2080 GPU.

**Comment by palmdong** [comment]
Hey @angelika1108, thanks a lot for the helpful reply. Have a nice day.
