### ISSUE TITLE
Visualization of the results

### ISSUE THREAD

**Issue by iuliaalda** [valeoai/rangevit#8]
Hello, 
after the test run on nuScenes I obtained the acc/iou/recall values and the *_lidarseg.bin files, but I am not sure how I can visualize the predicted segmentations for the point clouds.
Thank you!

**Comment by gidariss** [comment]
Hello. For the visualizations we used the CloudCompare (https://cloudcompare.org/). 
It requires to first save the point clouds with the predicted classes in a file.  
CloudCompare reads files in various formats. The easiest is to write files (.xyz) with following structure:
x0 y0 z0 a0 b0 c0 ...
x1 y1 z1 a1 b1 c1 ...
x2 y2 z2 a2 b2 c2 ...
x3 y3 z3 a3 b3 c3 ...
where xi yi zi are the coordinates of the points and the ai bi ci... are the scalar fields associated with the points (can be the label id).

**Comment by hoangthanh1234** [comment]
Hello! Can you provide more detail on visualization process Or provide the code to convert lidarseg.bin to new format?
