### ISSUE TITLE
Mini version or the full vision of the nuScenes dataset

### ISSUE THREAD

**Issue by Amazingren** [valeoai/rangevit#9]
Dear all, 

I hope you are doing well! And thanks for the nice work!

I would like to know if you are using the mini version of the full nuScenes dataset in your paper.

Best regards and have a nice day,

**Comment by angelika1108** [comment]
Hi @Amazingren! 
We thank you very much for your question! We didn't use the mini nuScenes in the paper (only for debugging). All models were trained on the full train split of nuScenes, and the results are reported on the full validation split. 
Best wishes and have a nice day as well,

**Comment by Amazingren** [comment]
> Hi @Amazingren! We thank you very much for your question! We didn't use the mini nuScenes in the paper (only for debugging). All models were trained on the full train split of nuScenes, and the results are reported on the full validation split. Best wishes and have a nice day as well,

got it! thanks a lot!
